# Generated by Django 5.1.6 on 2025-03-22 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0002_alter_task_options_alter_task_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='Task.task')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['owner'], name='TimeEntry_t_owner_i_6b3550_idx'), models.Index(fields=['task'], name='TimeEntry_t_task_id_cb8c92_idx'), models.Index(fields=['start_time'], name='TimeEntry_t_start_t_0572e3_idx'), models.Index(fields=['end_time'], name='TimeEntry_t_end_tim_dec906_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_gt_start_time')],
            },
        ),
    ]
