# Generated by Django 5.1.6 on 2025-04-26 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='Task.task')),
            ],
            options={
                'verbose_name_plural': 'Time entries',
                'ordering': ['-end_time'],
                'indexes': [models.Index(fields=['owner'], name='TimeEntry_t_owner_i_6b3550_idx'), models.Index(fields=['task'], name='TimeEntry_t_task_id_cb8c92_idx'), models.Index(fields=['start_time'], name='TimeEntry_t_start_t_0572e3_idx'), models.Index(fields=['end_time'], name='TimeEntry_t_end_tim_dec906_idx'), models.Index(fields=['duration'], name='TimeEntry_t_duratio_379a7b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_gt_start_time', violation_error_message='Value for `end_time` field must be after `start_time`.')],
            },
        ),
    ]
