# Generated by Django 5.1.6 on 2025-03-23 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_task_unique_task_name_per_owner_and_more'),
        ('TimeEntry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Time entries'},
        ),
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='end_time_gt_start_time',
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_gt_start_time', violation_error_message='Value for `end_time` field must be after `start_time`.'),
        ),
    ]
