# Generated by Django 5.1.6 on 2025-03-23 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_options_alter_task_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_name_per_owner',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_task_name_per_owner', violation_error_message='Task name must be unique per owner.'),
        ),
    ]
